/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  label1 = new GLabel(this, 10, 10, 50, 20);
  label1.setText("Action:");
  label1.setOpaque(false);
  lblAction = new GLabel(this, 60, 10, 280, 20);
  lblAction.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblAction.setOpaque(false);
  compass = new GSketchPad(this, 350, 10, 42, 42);
  lblHeading = new GLabel(this, 340, 50, 60, 20);
  lblHeading.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblHeading.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel lblAction; 
GSketchPad compass; 
GLabel lblHeading; 

