/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btnDrop_press(GButton source, GEvent event) { //_CODE_:btnDrop:625097:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());
  bot.dropItems();
} //_CODE_:btnDrop:625097:

public void btnChop_press(GButton source, GEvent event) { //_CODE_:btnChop:426480:
  //println("btnChop - GButton >> GEvent." + event + " @ " + millis());
  bot.chopTree();
} //_CODE_:btnChop:426480:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  label1 = new GLabel(this, 10, 10, 50, 20);
  label1.setText("String:");
  label1.setOpaque(true);
  lblAction = new GLabel(this, 70, 10, 270, 20);
  lblAction.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblAction.setOpaque(true);
  compass = new GSketchPad(this, 350, 10, 42, 42);
  lblHeading = new GLabel(this, 350, 50, 50, 20);
  lblHeading.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblHeading.setOpaque(false);
  lblMatch = new GLabel(this, 70, 40, 270, 20);
  lblMatch.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblMatch.setOpaque(true);
  label2 = new GLabel(this, 10, 40, 50, 20);
  label2.setText("Match:");
  label2.setOpaque(true);
  padGame = new GSketchPad(this, 25, 101, 260, 170);
  lblFPS = new GLabel(this, 325, 274, 120, 20);
  lblFPS.setOpaque(false);
  label3 = new GLabel(this, 342, 73, 73, 21);
  label3.setText("Bot State:");
  label3.setOpaque(false);
  lblState = new GLabel(this, 401, 74, 44, 20);
  lblState.setText("Idle");
  lblState.setOpaque(false);
  btnDrop = new GButton(this, 340, 150, 80, 30);
  btnDrop.setText("Drop Items");
  btnDrop.addEventHandler(this, "btnDrop_press");
  btnChop = new GButton(this, 340, 110, 80, 30);
  btnChop.setText("Chop Tree");
  btnChop.addEventHandler(this, "btnChop_press");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel lblAction; 
GSketchPad compass; 
GLabel lblHeading; 
GLabel lblMatch; 
GLabel label2; 
GSketchPad padGame; 
GLabel lblFPS; 
GLabel label3; 
GLabel lblState; 
GButton btnDrop; 
GButton btnChop; 

